### ISSUE TITLE
Error during submision on ZeroCost Competition

### ISSUE THREAD

**Issue by lichuanx** [automl/NASLib#112]
Hi, I come across this error after submitting it to Coda-Lab and I believed it should have been something wrong in the evaluation system.

> Traceback (most recent call last):
>   File "/worker/worker.py", line 705, in run
>     put_blob(stdout_url, stdout_file)
>   File "/worker/worker.py", line 214, in put_blob
>     'x-ms-version': '2018-03-28',
>   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 99, in put
>     return request('put', url, data=data, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 44, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 335, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 438, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 324, in send
>     raise ConnectionError(sockerr)
> ConnectionError: [Errno -3] Temporary failure in name resolution

**Comment by Neonkraft** [comment]
Hi,

Thanks a lot for bringing this to our attention. Yes, it looks like an issue in our evaluation system. We're currently looking into it, and will let you know as soon as it is resolved.

Best
Arjun

**Comment by Neonkraft** [comment]
The problem has been addressed. Your submission will now run :) Please feel free to close this issue after ensuring it does.

Thanks again for bringing this to our attention. We hope you enjoy the competition!

**Comment by lichuanx** [comment]
> The problem has been addressed. Your submission will now run :) Please feel free to close this issue after ensuring it does.
> 
> Thanks again for bringing this to our attention. We hope you enjoy the competition!

Thank you! Problem solved, and I closed the issue.
