### ISSUE TITLE
Setup script fails

### ISSUE THREAD

**Issue by georgiachanning** [automl/NASLib#126]
When running the `pip install -e .` command, set up fails. It seems tripped up on the numpy installation, but numpy is already installed (version consistent with that required). 
<img width="1512" alt="Screen Shot 2022-07-07 at 3 00 37 PM" src="https://user-images.githubusercontent.com/48959510/177851640-e313d9b3-868a-4f2e-b6f2-61fc1ec453c7.png">
See error message above. The result is consistent across three different systems: M1 Mac and two Linux. Although not making the entire set up script fail, torchaudio also cannot be installed with the command suggested under Set Up in the NASLib docs. Additionally, it seems many of the packages specified in requirements.txt seem to have conflicts.

**Comment by shashankskagnihotri** [comment]
Hi, 
the setup script you are running is from which branch?

**Comment by shashankskagnihotri** [comment]
Hi,
the setup in the Develop branch works perfectly fine without any conflicts (if any, they are automatically resolved by pip). If you are still having issues, please feel free to open a new issue.
