### ISSUE TITLE
Zero-Cost Predictor - Run on all 15,625 architecture for NasBench201

### ISSUE THREAD

**Issue by alec-flowers** [automl/NASLib#142]
Hi, I wanted to test a Zero-Cost Predictor on all 15,625 architectures for NASBench201. In the [NAS-Bench-Suite-Zero](https://arxiv.org/pdf/2210.03230.pdf) paper you state that you did this for all the architectures - 

> For all NAS-Bench-201 and TransNAS-Bench-101 tasks, we evaluate all ZC proxy values and the respective runtimes, for all architectures

But I am running across some issues. In the [predictor_config.yaml](https://github.com/automl/NASLib/blob/Develop/naslib/runners/predictors/predictor_config.yaml) it only has an option for random sampling of architectures with the parameter **uniform_random**. 

I wrote my own code to exhaustively sample all architectures using _naslib.search_spaces.nasbench201.graph.get_arch_iterator()_. However, _PredictorEvaluator.load_dataset()_ then loads 15,625 graphs into a list, which around 6,000 architectures in, requires too much memory for my computer. I wanted to see if I was going about this the best way or if there was a better way.

Thanks.

**Comment by Neonkraft** [comment]
Hi @alec-flowers 

Thank you for your interest in our project! You'll find that all the code relating to zero cost proxies are in the `zerocost` branch. You can edit [this runner file](https://github.com/automl/NASLib/blob/zerocost/naslib/runners/benchmarks/runner.py) to run your proxies on all the nb201 models.  

Best,
Arjun
