### ISSUE TITLE
Drive links no longer exist

### ISSUE THREAD

**Issue by javieryu** [automl/NASLib#146]
The download script `source scripts/bash_scripts/download_nbs_zero.sh all` no longer works, and it seems like the drive folders do not exist anymore. Is this data hosted somewhere else? This is for the running the correlation results of the `zerocost` branch.

**Comment by rtu715** [comment]
Hi, this is an issue with the google drive, and we're working on restoring the original links. Meanwhile, please use this link to download all the NBZCP evaluations: https://drive.google.com/file/d/1AvX5B0qBUA3hsItyn2to4GeCBJzSWTpg/view?usp=sharing.
