### ISSUE TITLE
TransNAS-Bench-101 Download

### ISSUE THREAD

**Issue by Tongzhou0101** [automl/NASLib#172]
Hi, the download link of TransNAS-Bench-101 is invalid now. I wonder if anyone has the data file and would like to share it with me. Thanks for the help!

**Comment by AnaRisnoveanu** [comment]
I encountered the same issue. They provided the link for the model [somewhere else](https://github.com/yawen-d/TransNASBench/issues/6) and the dataset I got by following the instructions [here](https://github.com/StanfordVL/taskonomy/blob/master/data/README.md). But that took up a lot of space and also downloaded tasks I did not want. Did you manage to get only the datasets that you needed?

**Comment by AnaRisnoveanu** [comment]
Oh, I found the [link](https://docs.omnidata.vision/starter_dataset_download.html#Examples) which explains how to download only the taxonomy dataset from Omnitools. Further on, to download datasets for taxonomy-mini then I had to run the files inside that folder.
