### ISSUE TITLE
Extra .json files for zc_intro.py

### ISSUE THREAD

**Issue by AnaRisnoveanu** [automl/NASLib#178]
I am running tutorial/zc_intro.py and it returns this error:
`[Errno 2] No such file or directory: '/home.../naslib/data/zc_nasbench201.json'

  File "/home.../naslib/utils/get_dataset_api.py", line 24, in get_zc_benchmark_api
    with open(datafile_path) as f:
  File "/home.../tutorial/zc_intro.py", line 113, in <module>
    zc_api = get_zc_benchmark_api('nasbench201', 'cifar10')

FileNotFoundError: [Errno 2] No such file or directory: '/home.../naslib/data/zc_nasbench201.json'`

I have already checked the data for the benchmark but this file was not there to download.

**Comment by abhash-er** [comment]
Hi @AnaRisnoveanu, 

You could run the following bash script to download the missing json file:
```bash 
bash scripts/zc/bash_scripts/download_nbs_zero.sh nb201
```
You could also pass the arguments `nb101`, `nb301`, and `tnb101` to this bash script for the respective search spaces. 

Alternatively, you can also download using these drive links:
[NB101](https://drive.google.com/file/d/1Rkse44EWgYdBS34iyhjSs9Y2l0fxPCpU/view?usp=share_link)
[NB201](https://drive.google.com/file/d/1R7n7GpFHAjUZpPISzbhxH0QjubnvZM5H/view?usp=share_link)
[NB301](https://drive.google.com/file/d/1RddgmwqjWJ1czGT8gEPB8qqhUHazp92G/view?usp=share_link)
[TNB101-Macro](https://drive.google.com/file/d/1teH8JcQsamZngUD_DMQyNkCoUYYSTM0M/view?usp=share_link)
[TNB101-Micro](https://drive.google.com/file/d/1SBOVAyhLCBTAJiU_fo7hLRknNrGNqFk7/view?usp=share_link)

We will soon update the readme about it.

**Comment by AnaRisnoveanu** [comment]
Thank you, zc_intro.py works fine now NAS-Benchmark-201. 

When I set it to NAS-Benchmark-101, I get an error in  `score = zc_api[str(spec)][pred]['score']` on line 118.  There is no _str(spec)_ in the keys of _zc_api_.

`Exception has occurred: KeyError
'(0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 2, 3, 3, 1)'
  File "/home/anamariar/topush/experimental.nas_ebs/tutorial/zc_intro.py", line 118, in <module>
    score = zc_api[str(spec)][pred]['score']
KeyError: '(0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 2, 3, 3, 1)'`

**Comment by abhash-er** [comment]
There are **423624** total architectures available in `NASBench101` with `CIFAR10`, but we only have a list of around **10000** in the **NASBench101 zero-cost benchmark**. That's the reason you are getting this error. 

The search spaces having an exhaustive list of the zero-cost benchmarks are only NasBench201, TNB101 Micro, and  TNB101 Macro. 

You may also refer to the [NAS-Bench-Suite-Zero](https://arxiv.org/pdf/2210.03230.pdf) paper for exact numbers and read more about the reports regarding using zero-cost proxies with NAS.
