### ISSUE TITLE
Val_accuracy is negative for "room_layout " in "zc_transbench101_micro.json" and "zc_transbench101_macro.json"

### ISSUE THREAD

**Issue by SliverySky** [automl/NASLib#188]
I download "zc_transbench101_micro.json" from the given link (https://drive.google.com/file/d/1SBOVAyhLCBTAJiU_fo7hLRknNrGNqFk7/view). Then, I found the **val_accuracy** is negative for the **room_layout** dataset. Similar situation happens in the **room_layout** dataset for" zc_transbench101_macro.json".

**Comment by Neonkraft** [comment]
Hi @SliverySky ,

Thank you for your interest in our work!

The `room-layout` task of Trans-NAS-Bench-101 is to estimate a 3d bounding box, and as such, it does not have accuracy as a metric. This task uses MSE Loss as its metric. The `zc_transbench101_{micro/macro}.json` benchmarks used the keyword "val_accuracy" for uniformity when consuming the API (as the metric to maximize).  

I hope this helps!

![Screenshot from 2024-09-16 14-38-54](https://github.com/user-attachments/assets/7e24520c-deb6-44fe-99c4-699c4051b659)

**Comment by SliverySky** [comment]
Thank you very much for your answer!
