### ISSUE TITLE
Error loading notebook 

### ISSUE THREAD

**Issue by jinningli** [automl/NASLib#53]
Hi,

I cannot open https://github.com/automl/NASLib/blob/master/examples/naslib_tutorial.ipynb either with my Chrome or after I download it and run locally. I suppose this file is broken. Could you help have a look?

```
Unreadable Notebook: NASLib-Develop/examples/naslib_tutorial.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n ...',)
```

Thanks,
Jinning

**Comment by shashankskagnihotri** [comment]
Dear Jinning,
Please use the Develop branch to view the notebook, it has been fixed there.

Regards
Shashank
