### ISSUE TITLE
Randomly sample architectures/cell from Search Spaces

### ISSUE THREAD

**Issue by geantrindade** [automl/NASLib#80]
I am trying, without success, sampling random architectures from the defined Search Spaces such as DARTS and SimpleCell spaces. 

Is it possible to sample an entire PyTorch object representing the whole architecture? If not, is it possible to sample all the possible cells from the search spaces? Can you provide some code examples for doing this?

Thanks.

**Comment by geantrindade** [comment]
Nothing yet?

**Comment by crwhite14** [comment]
Hi, thank you for your interest. Many of the search spaces in NASLib have a `sample_random_architecture()` method, for example, the one for darts is [here](https://github.com/automl/NASLib/blob/047b0e66f034c5fb91df8e93efc30a12c6bc2259/naslib/search_spaces/darts/graph.py#L476), and an example on how to use it is in the random search NAS algorithm [here](https://github.com/automl/NASLib/blob/047b0e66f034c5fb91df8e93efc30a12c6bc2259/naslib/optimizers/discrete/rs/optimizer.py#L63). Currently SimpleCell does not have this method.

**Comment by geantrindade** [comment]
Thank you @crwhite14 ! I was able to sample some random genotypes from DARTS already, but I was wondering if it is possible to customize the search space, maybe using simpleCell or DARTS to create other popular NAS spaces such as ProxylessNAS, NASNet, ENAS, etc. Is that possible? Do you have any examples to show me? Thank you so much for the support you are giving me.

**Comment by crwhite14** [comment]
Currently NASLib focuses on queryable benchmarks such as NAS-Bench-101/201/301/NLP/ASR, to make NAS research easier. You are free to write your own customized search space. For each search space, the architectures are created in the `__init__` method of the `graph.py` file. For example, for DARTS it is lines 83-192 [here](https://github.com/automl/NASLib/blob/047b0e66f034c5fb91df8e93efc30a12c6bc2259/naslib/search_spaces/darts/graph.py#L83).
