### ISSUE TITLE
NasBench-201 Benchmark API

### ISSUE THREAD

**Issue by zekikus** [automl/NASLib#88]
Hi,

How can I download nb201_cifar10_full_training.pickle, nb201_cifar100_full_training.pickle and nb201_ImageNet16_full_training.pickle files? I can't find these files. Can you help me?

Thanks

**Comment by arberzela** [comment]
Hi,

Our apologies for not updating the README with the link. Here you can find all the necessary files: https://drive.google.com/drive/folders/1IwkPM_MP1gPY_X8DF_0kCJc9ID1qxJDy?usp=sharing

Best,
Arber

**Comment by zekikus** [comment]
Hi,

Thank you for your help.

Best,
